env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
rules:
  "@typescript-eslint/ban-ts-comment":
    - warn
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
  sort-imports:
    - error
    - ignoreDeclarationSort: true
      ignoreCase: true
  eqeqeq:
    - error
  prefer-const:
    - error
    - destructuring: all
overrides:
  - files:
      - "**/*.js"
    rules:
      "@typescript-eslint/no-var-requires":
        - "off"
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: "./tsconfig.json"
